FROM pimcore/pimcore:php8.1-v1-dev

USER root

RUN apt-get update && \
    apt-get install -y wget apt-transport-https gnupg lsb-release && \
    wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | gpg --dearmor -o /usr/share/keyrings/trivy.gpg && \
    echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb generic main" | tee /etc/apt/sources.list.d/trivy.list && \
    apt-get update && \
    apt-get install -y trivy && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN mkdir -p /var/www/.cache && \
    chown -R www-data:www-data /var/www/.cache

ENV XDG_CACHE_HOME=/var/www/.cache

USER www-data

WORKDIR /var/www/html

# Run: docker exec <container> trivy filesystem --severity HIGH,CRITICAL --format table /
CMD ["tail", "-f", "/dev/null"]
