name: Docker Build & Release

on:
    workflow_dispatch:
        inputs:
            publish:
                description: 'Publish images to registries'
                required: false
                default: true
                type: boolean
    push:
        tags:
            - 'v*.*'
    schedule:
        -   cron: '30 2 * * 1,3,5'

env:
    IMAGE_NAME: s1kom/pimcore-custom

jobs:
    build-php:
        name: "Build PHP images"
        runs-on: ${{ matrix.runner }}
        if: github.repository == 'studio1gmbh/pimcore-docker'
        strategy:
            matrix:
                runner:
                    - ubuntu-22.04
                    - ubuntu-22.04-arm
                build:
                    #- { tag: '1.x', php: '8.1', distro: bullseye, version-override: "v1-dev", latest-tag: false }
                    #- { tag: '1.x', php: '8.2', distro: bullseye, version-override: "v1-dev", latest-tag: false }
                    #- { tag: 'v1.5', php: '8.1', distro: bullseye, version-override: "", latest-tag: true }
                    #- { tag: 'v1.5', php: '8.2', distro: bullseye, version-override: "", latest-tag: false }
                    #- { tag: 'v2.2', php: '8.2', distro: bullseye, version-override: "", latest-tag: false }
                    #- { tag: '2.x', php: '8.2', distro: bullseye, version-override: "v2-dev", latest-tag: false }
                    #- { tag: 'v3.7', php: '8.2', distro: bookworm, version-override: "", latest-tag: true }
                    #- { tag: 'v3.7', php: '8.3', distro: bookworm, version-override: "", latest-tag: true }
                    #- { tag: '3.x', php: '8.2', distro: bookworm, version-override: "v3-dev", latest-tag: false }
                    #- { tag: '3.x', php: '8.3', distro: bookworm, version-override: "v3-dev", latest-tag: false }
                    - { tag: 'v4.0-1', php: '8.4', distro: bookworm, version-override: "", latest-tag: true }
                    #- { tag: '4.x', php: '8.4', distro: bookworm, version-override: "v4-dev", latest-tag: false }


        steps:
            -   uses: actions/checkout@v4
                with:
                    ref: ${{ matrix.build.tag }}

            -   name: Login to DockerHub Registry
                run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

            -   name: Login to GitHub Container Registry
                run: echo ${{ secrets.IMAGES_REPO_TOKEN }} | docker login ghcr.io -u ${{ secrets.IMAGES_REPO_USERNAME }} --password-stdin

            -   name: Configure and build images
                id: vars
                env:
                    VERSION_OVERRIDE: "${{ matrix.build.version-override }}"
                    ARCH_TAG: ${{ contains(matrix.runner, 'arm') && 'arm64' || 'amd64' }}
                    PUSH: ${{ github.event_name != 'workflow_dispatch' || inputs.publish }}
                run: |
                    set -eux;
                    sudo apt-get update

                    echo ${{ matrix.runner}}

                    if [[ "${{ matrix.build.tag }}" =~ ^v?1.[0-9x]+$ ]]; then
                        imageVariants=("fpm" "debug" "supervisord")
                    else
                        imageVariants=("min" "default" "max" "debug" "supervisord")
                    fi
                    for imageVariant in ${imageVariants[@]}; do
                        echo "Building image variant $imageVariant"
                        DOCKER_PLATFORMS=linux/amd64,linux/arm64
                        PHP_VERSION=${{ matrix.build.php }}
                        DEBIAN_VERSION="${{ matrix.build.distro }}"
                        VERSION="${{ matrix.build.tag }}"
                        # for the latest dev branch we use "dev" as the version and not the name of the branch
                        if [ ! -z "$VERSION_OVERRIDE" ]; then
                            VERSION="$VERSION_OVERRIDE"
                        fi
                        PHP_SUB_VERSION=$(docker run -i --rm php:${{ matrix.build.php }}-fpm-${{ matrix.build.distro }} php -r 'echo PHP_VERSION;')
                        if [ "$imageVariant" = "fpm"  ] || [ "$imageVariant" = "default"  ]; then
                            BASE_TAG="php${{ matrix.build.php }}"
                            BASE_TAG_DETAILED="php${PHP_SUB_VERSION}"
                        else
                            BASE_TAG="php${{ matrix.build.php }}-$imageVariant"
                            BASE_TAG_DETAILED="php${PHP_SUB_VERSION}-$imageVariant"
                        fi
                        # DEBUG / TEST
                        #BASE_TAG="testv3-$BASE_TAG"
                        #BASE_TAG_DETAILED="testv3-$BASE_TAG_DETAILED"


                        TAG="${BASE_TAG}-${VERSION}-${ARCH_TAG}"
                        TAG_DETAILED="${BASE_TAG_DETAILED}-${VERSION}-${ARCH_TAG}"

                        GHCR_TAG="ghcr.io/pimcore/pimcore:${TAG}"
                        GHCR_TAG_DETAILED="ghcr.io/pimcore/pimcore:${TAG_DETAILED}"

                        TAGS="--tag ${IMAGE_NAME}:${TAG}"
                        TAGS="$TAGS --tag ${IMAGE_NAME}:${TAG_DETAILED}"

                        TAGS="$TAGS --tag $GHCR_TAG"
                        TAGS="$TAGS --tag $GHCR_TAG_DETAILED"

                        # Tag latest with Version build too
                        if [ "true" = "${{ matrix.build.latest-tag }}" ]; then
                            TAGS="$TAGS --tag ${IMAGE_NAME}:${BASE_TAG}-latest-${ARCH_TAG}"
                            TAGS="$TAGS --tag ghcr.io/pimcore/pimcore:${BASE_TAG}-latest-${ARCH_TAG}"
                        fi
                        # Create tag for major version
                        if [[ $VERSION =~ ^v[0-9]+.[0-9]+$ ]]; then
                            VERSION_MAJOR="${VERSION//.[0-9]/}"
                            TAG_MAJOR="${BASE_TAG}-${VERSION_MAJOR}-${ARCH_TAG}"
                            GHCR_TAG_MAJOR="ghcr.io/pimcore/pimcore:${TAG_MAJOR}"
                            TAGS="$TAGS --tag ${IMAGE_NAME}:${TAG_MAJOR}"
                            TAGS="$TAGS --tag $GHCR_TAG_MAJOR"
                        fi

                        docker build --output "type=image,push=$PUSH" \
                            --target="pimcore_php_$imageVariant" \
                            --build-arg PHP_VERSION="${PHP_VERSION}" \
                            --build-arg DEBIAN_VERSION="${DEBIAN_VERSION}" \
                            ${TAGS} .

                        docker inspect ${IMAGE_NAME}:${TAG} || true;

                        # Only aggregate tags if we're publishing
                        if [[ "$PUSH" == "true" ]]; then
                            CLEAN_TAGS="${TAGS//-arm64/}"
                            CLEAN_TAGS="${CLEAN_TAGS//-amd64/}"
                            CLEAN_TAGS="${CLEAN_TAGS//--tag /}"

                            read -r -a TAGS_ARRAY <<< "$CLEAN_TAGS"
                                                  
                            for tag in "${TAGS_ARRAY[@]}"; do
                                echo "Processing tag: $tag"
                                echo "$tag" >> aggregated_tags.txt
                            done
                        fi

                    done

            -   name: Upload aggregated tags
                if: github.event_name != 'workflow_dispatch' || inputs.publish
                uses: actions/upload-artifact@v4
                with:
                    name: aggregated_tags_${{ matrix.runner }}_${{ matrix.build.tag }}_${{ matrix.build.php }}_${{ matrix.build.distro }}_${{ matrix.build.version-override }}_${{ matrix.build.latest-tag }}
                    path: aggregated_tags.txt

    process-tags:
        runs-on: ubuntu-22.04
        needs: build-php
        if: github.event_name != 'workflow_dispatch' || inputs.publish
        steps:

            -   name: Login to DockerHub Registry
                run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

            -   name: Login to GitHub Container Registry
                run: echo ${{ secrets.IMAGES_REPO_TOKEN }} | docker login ghcr.io -u ${{ secrets.IMAGES_REPO_USERNAME }} --password-stdin

            -   name: Download aggregated tags
                uses: actions/download-artifact@v4
                with:
                    path: artifacts

            -   name: Process tags
                run: |
                    find artifacts -type f -name "aggregated_tags.txt" -exec cat {} + > all_aggregated_tags.txt

                    readarray -t TAGS_ARRAY < all_aggregated_tags.txt

                    declare -A UNIQUE_TAGS
                    for tag in "${TAGS_ARRAY[@]}"; do
                        UNIQUE_TAGS["$tag"]=1
                    done

                    for tag in "${!UNIQUE_TAGS[@]}"; do
                    
                        echo "Processing tag: $tag"
                        
                        docker manifest create "$tag" \
                        --amend "${tag}-amd64" \
                        --amend "${tag}-arm64"

                        docker manifest push "$tag"
    
                    done

